version: '3.8'
services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=alurafood-pagamento
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local

#allowPublicKeyRetrieval=true para subir o banco: user e senha root
